version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: ~/tndavaloz/table-setting
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package.lock" }}
      - run: npm install
      - save_cache:
          key: v1-npm-{{ checksum "package.lock" }}
          paths:
            - ./node_modules
      - run: npm run build
workflows:
  version: 2
  build-on-master:
    jobs:
      - build
          filters:
            branches:
              only: master